name: Run HCDC on the PR branch

on:
  pull_request:

jobs:
  run-hcdc:
    runs-on: ubuntu-latest

    env:
      PR_BRANCH: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Auth token
        env:
          OS_USERNAME: ${{ secrets.OTC_HCDC_USERNAME }}
          OS_PASSWORD: ${{ secrets.OTC_HCDC_PASSWORD }}
          OS_DOMAIN_NAME: ${{ secrets.OTC_HCDC_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OTC_HCDC_PROJECT_NAME }}
        shell: bash
        run: |
          cat > body.json <<EOF
            {
                "auth": {
                    "identity": {
                        "password": {
                            "user": {
                            "name": "${OS_USERNAME}",
                            "password": "${OS_PASSWORD}",
                            "domain": { "name": "${OS_DOMAIN_NAME}" }
                            }
                        },
                        "methods": [
                            "password"
                        ]
                    },
                    "scope": { 
                        "project": { 
                            "name": "${OS_PROJECT_NAME}" 
                        }
                    }
                }
            }
            EOF

          # Get the token
          RESP_HEADERS=$(mktemp)
          curl -sS -D "$RESP_HEADERS" -o /dev/null \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -X POST "https://iam.eu-de.otc.t-systems.com/v3/auth/tokens" \
            -d "$JSON"

          TOKEN=$(grep -i "^X-Subject-Token:" "$RESP_HEADERS" | awk '{print $2}' | tr -d '\r')
          if [ -z "$TOKEN" ]; then
            echo "Failed to obtain token" >&2
            echo "Response headers:" >&2
            cat "$RESP_HEADERS" >&2
            exit 1
          fi

          # Export token and mask it
          echo "AUTH_TOKEN=$TOKEN" >> "$GITHUB_ENV"
          echo "::add-mask::$TOKEN"

      - name: Run hcdc
        shell: bash
        run: |
          hcdc --branch "$PR_BRANCH"
